Cs 43
maryvilledev/codesplain pull request #44
Opened 2017-03-30 16:46 UTC by JWalker1995

2017-04-06 15:30 UTC, Hopding commented
@JWalker1995 Can you please link this PR to an issue, and explain what this is doing?

2017-04-06 20:47 UTC, thebho commented
Still looking for a description on this PR

2017-04-07 14:16 UTC, Hopding commented
Cross posting what Joel posted on #43:
> Changes to the AST node format:
> 1. The antlr node type is now stored in the `ast_type` property.
> 2. The `tags` property is now an array of "things" that the tag is. UI highlighting should depend solely on this property.
> 3. There is a `detail` property, which is an array of objects that contain extra details about the node. This is somewhat of a catch-all container, but will probably be used mostly to store documentation links and stuff like that. Each object in the array must have a `handler` property that specifies a function that handles the rest of the object.

2017-04-07 14:27 UTC, Hopding requested changes
Looks good, except for the one change I requested.

2017-04-07 14:27 UTC, Hopding commented on public/index.html
> +        let parser = window['Codesplain_parse_' + lang_el.value];
This should be `window['CodesplainParser']`, per the change made in https://github.com/maryvilledev/codesplain/commit/c2ca09c1f5b9dc5702e351e04c41db872d598c8e.

2017-04-07 14:53 UTC, Hopding approved these changes

2017-04-11 14:10 UTC, merged