Added CSV Mapping Files For Language Rules
maryvilledev/codesplain pull request #53
Opened 2017-04-07 13:17 UTC by Hopding

## Description

This PR adds a node script, `gencsv`, which can be used to convert a `language_configs/{{language}}.rules.js` file's rules into a csv file located in `/mappings` directory. A test has also been added, `mappings.js`, which inspects these mapping CSV files to ensure that they have all the required rules, and that enabled rules have a pretty name and color specified. If this test passes and the branch is merged in GitHub, Circle will deploy the CSV mapping files to the same bucket as their respective parsers.

## Motivation and Context

Fixes https://github.com/maryvilledev/codesplainUI/issues/311.

## Checklist:

- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

## Screenshots (if appropriate):

2017-04-07 15:32 UTC, thebho approved these changes

2017-04-07 16:56 UTC, thejoelw requested changes

2017-04-07 16:56 UTC, JWalker1995 commented on .gitattributes
> +*.csv binary
Should CSV files really be binary? In my opinion they're human readable/writable and it would be nice to be able to see what changed in a commit.

2017-04-10 14:08 UTC, Hopding commented
@JWalker1995 Do you approve of merging this PR now?

2017-04-12 14:56 UTC, merged